### PR TITLE
Add combo security scheme

### PR DESCRIPTION
**Pull request by dodomorandi**
I would like an opinion about the signature of `all_of`/`one_of`. Currently, I am requiring an `I: IntoIterator<Item = String>`, which leads to some ergonomic rough edges for the user. In fact, I initially wanted to to something like:

```rust
pub fn all_of<I, T>(
    self,
    iter: I,
) -> SecuritySchemeBuilder<(AllOfComboSecuritySchemeTag, Vec<String>)>
where
    I: IntoIterator<Item = T>,
    T: Into<String>
```

but I am a bit worried about eventual issues I am not thinking about (i.e. missing type deduction in some cases). I cannot think about a function in the `std` that takes this kind of generic `IntoIterator`, maybe there could be a reason for this. What do you think @lu-zero?

### CODE REVIEW

**Comment by lu-zero** [comment]
Would be nice to have, what breaks if you try to use that signature?

**Review by lu-zero — APPROVED** [review]
Either way it is good IMHO.

**Comment by dodomorandi** [comment]
In the end I tried the solution using `I: IntoIterator<Item = T>, T: Into<String>`, it seems to be a nice ergonomic improvement. If we discover some downsides in the future we can easily change it back (with a breaking change, but we need to experiment).

**Review by lu-zero — APPROVED** [review]

**Comment by lu-zero** [comment]
Sounds good to me.

**Pull request merged**
